// Code generated by "stringer -type=NetworkType -output=network_type.strings.go"; DO NOT EDIT.

package node

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Udp-1]
	_ = x[Tcp-2]
	_ = x[Unix-3]
}

const _NetworkType_name = "UnknownUdpTcpUnix"

var _NetworkType_index = [...]uint8{0, 7, 10, 13, 17}

func (i NetworkType) String() string {
	if i >= NetworkType(len(_NetworkType_index)-1) {
		return "NetworkType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NetworkType_name[_NetworkType_index[i]:_NetworkType_index[i+1]]
}
